### PR TITLE
fix: update sfdx command to sf to match dependent command id change

### PR DESCRIPTION
**Pull request by ben-zhang-at-salesforce**
salesforcedx-vscode-core changed all sfdx.* command to sf.*. we need to match the change

### CODE REVIEW

**Review by maliroteh-sf — COMMENTED** [review]
Need to fix prettier issues so that CI jobs all pass.

**Review by khawkins — APPROVED** [review]
Looks like this needs `npm run prettier:write` changes committed, but other than that LGTM!

**Comment by ben-zhang-at-salesforce** [comment]
now this pr is failing with same error as https://github.com/salesforce/salesforcedx-vscode-mobile/pull/67

**Comment by maliroteh-sf** [comment]
> now this pr is failing with same error as #67

@ben-zhang-at-salesforce wait for the fix in #67 to go in, then rebase and you should be good to go.

**Pull request merged**
