### PR TITLE
chore: upgrade to node >=20

### PR DESCRIPTION
**Pull request by maliroteh-sf**
### What does this PR do?
Upgrade to node >=20

### CODE REVIEW

**Comment by sfdctaka** [comment]
Do we want to delete package-lock.json?

**Comment by maliroteh-sf** [comment]
> Do we want to delete package-lock.json?

@sfdctaka This repo does not use `yarn` so did you mean whether we want to delete `package-lock.json` and then run `npm install` to regenerate the file with updated dep versions? We now have dependabot for such things so I didn't do such update in this PR and tried to keep it as simple as possible.

**Comment by sfdctaka** [comment]
I made a mistake. I thought github had package-lock.json as deleted. Instead, the file is too big it didn't show the diff by default.

**Comment by khawkins** [comment]
Or...do you think we deleted it and that's the question? 😀 FWIW I don't see anything amiss with `package-lock.json` in this PR.

**Review by sfdctaka — APPROVED** [review]
LGTM!

**Pull request merged**
