### PR TITLE
Fix packaging

### PR DESCRIPTION
**Pull request by sfdctaka**
### What does this PR do?
Root of all evil was symbolic links to the subprojects(`lsp/server` and `lsp/client`).

`npx vsce package` was failing because `vsce` is not capable of zipping up code from those projects. The entire project was set up as npm workspace when `lsp` was introduced. **npm workspace** has its benefits, however, when it is used the subprojects become dependent packages inside `node_modules` where using sym link is used to point back to the paths where those projects reside. `vsce packaging` command, as it iterates through `node_module`, when it encounters symlink crashes.

The solution is to ditch **npm workspace**. It's a nice to have but not necessary in this project. Code can be shared directly without **npm workspace** playing middleman. A simple monorepo is more than adequate for this repo, for now.

This PR is minimal change that fixes packaging. Resurrect Offline Starter Kit Configuration Wizard. And makes the new feature(`lsp`) work for the first time in vsix.

To simplify dependency management, dependencies from `lsp/server` have been moved to the root's `package.json`.

Couple things to improve in the future:
* `TempProjectDirManager`, which was originally in the root project but now in `lsp/server`, should have a better home, perhaps another subproject to keep only utility functions, so it can be shared across all projects. It is also strange for it to be imported and then be exported, look `src/test/TestHelper.ts`.
* `lsp` could potentially be a separate distributable. Many public samples of `lsp` seem to do that. Whereas, we maybe strong coupling it with other features.

### CODE REVIEW

**Comment by sfdctaka** [comment]
When **npm workspace** is used `npx vsce package` crashes.

```
t.arai@tarai-ltmwdhj salesforcedx-vscode-mobile % npx vsce package
Executing prepublish script 'npm run vscode:prepublish'...

> salesforcedx-vscode-mobile@0.3.0 vscode:prepublish
> npm run clean && npm run compile && npm run bundle:extension

> salesforcedx-vscode-mobile@0.3.0 clean
> rimraf out ./lsp/server/out ./lsp/client/out

> salesforcedx-vscode-mobile@0.3.0 compile
> rimraf ./lsp/server/tsconfig.tsbuildinfo ./lsp/client/tsconfig.tsbuildinfo && tsc -b ./ && npm run copy-resources

> salesforcedx-vscode-mobile@0.3.0 copy-resources
> cp -r './lsp/server/resources' './lsp/server/out/'

> salesforcedx-vscode-mobile@0.3.0 cp3
> cp -r './images' './out/images'

> salesforcedx-vscode-mobile@0.3.0 cp4
> cp -r './LICENSE.txt' './out/LICENSE.txt'

> salesforcedx-vscode-mobile@0.3.0 bundle:extension
> esbuild ./src/extension.ts --bundle --outdir=out --format=cjs --target=es2020 --platform=node --external:vscode --external:@salesforce/core --external:@oclif/core --external:@salesforce/lwc-dev-mobile-core --minify --sourcemap

  out/extension.js      916.7kb
  out/extension.js.map    1.6mb

⚡ Done in 24ms
 WARNING  This extension consists of 16476 files, out of which 14654 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension. You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore.

 INFO  Files included in the VSIX:
salesforcedx-vscode-mobile-0.3.0.vsix
├─ [Content_Types].xml 
├─ extension.vsixmanifest 
└─ extension/
   ├─ LICENSE.txt [1.07 KB]
   ├─ README.md [1.79 KB]
   ├─ SECURITY.md [0.39 KB]
   ├─ package.json [6.37 KB]
   ├─ package.nls.json [0.98 KB]
   ├─ tsconfig.tsbuildinfo [1.88 KB]
   ├─ images/ (1 file) [6.64 KB]
   ├─ lsp/ (52 files) [956.4 KB]
   ├─ node_modules/ (16393 files) [53.41 MB]
   ├─ out/ (1 file) [916.73 KB]
   └─ resources/ (21 files) [30.5 KB]

=> Run vsce ls --tree to see all included files.

node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: not a file: /Users/t.arai/Documents/codebase/salesforcedx-vscode-mobile/node_modules/mobile-lsp-client
    at /Users/t.arai/Documents/codebase/salesforcedx-vscode-mobile/node_modules/yazl/index.js:31:52
    at FSReqCallback.oncomplete (node:fs:198:5)
Emitted 'error' event on ZipFile instance at:
    at /Users/t.arai/Documents/codebase/salesforcedx-vscode-mobile/node_modules/yazl/index.js:31:38
    at FSReqCallback.oncomplete (node:fs:198:5)
```

**Comment by sfdctaka** [comment]
When dependencies aren't consolidated at root's `package.json` an error is thrown.

```
t.arai@tarai-ltmwdhj salesforcedx-vscode-mobile % npx vsce package
      Executing prepublish script 'npm run vscode:prepublish'...
      
      > salesforcedx-vscode-mobile@0.3.0 vscode:prepublish
      > npm run clean && npm run compile && npm run bundle:extension
      
      
      > salesforcedx-vscode-mobile@0.3.0 clean
      > rimraf out ./lsp/server/out ./lsp/client/out
      
      
      > salesforcedx-vscode-mobile@0.3.0 compile
      > rimraf ./lsp/server/tsconfig.tsbuildinfo ./lsp/client/tsconfig.tsbuildinfo && tsc -b ./ && npm run copy-resources
      
      
      > salesforcedx-vscode-mobile@0.3.0 copy-resources
      > cp -r './lsp/server/resources' './lsp/server/out/'
      
      > salesforcedx-vscode-mobile@0.3.0 bundle:extension
      > esbuild ./src/extension.ts --bundle --outdir=out --format=cjs --target=es2020 --platform=node --external:vscode --external:@salesforce/core --external:@oclif/core --external:@salesforce/lwc-dev-mobile-core --sourcemap
      
      
        out/extension.js      916.7kb
        out/extension.js.map    1.6mb
      
      ⚡ Done in 27ms
       ERROR  The following files have the same case insensitive path, which isn't supported by the VSIX format:
        - extension/lsp/server/node_modules/@babel/traverse/tsconfig.tsbuildinfo
        - extension/lsp/server/node_modules/@babel/traverse/tsconfig.tsbuildinfo
        - extension/lsp/server/node_modules/@babel/traverse/package.json
        - extension/lsp/server/node_modules/@babel/traverse/package.json
        - extension/lsp/server/node_modules/@babel/traverse/README.md
        - extension/lsp/server/node_modules/@babel/traverse/README.md
        - extension/lsp/server/node_modules/@babel/traverse/LICENSE
        - extension/lsp/server/node_modules/@babel/traverse/LICENSE
        - extension/lsp/server/node_modules/@babel/traverse/lib/visitors.js
        - extension/lsp/server/node_modules/@babel/traverse/lib/visitors.js
        - extension/lsp/server/node_modules/@babel/traverse/lib/types.js
        - extension/lsp/server/node_modules/@babel/traverse/lib/types.js
        - extension/lsp/server/node_modules/@babel/traverse/lib/traverse-node.js
       // .... and many, many more
```

**Comment by sfdctaka** [comment]
The errors mentioned above were the two major ones. There were other errors that I encountered as I mangled **npm workspace** to get it to work but all a moot effort. The best was to just keep it simple.

**Comment by maliroteh-sf** [comment]
This is essentially undoing all the great work that was done to create subprojects and a workspace. I'm not sure how I feel about that.

Other repos like [this one](https://github.com/forcedotcom/salesforcedx-vscode) have it also set up as workspace and they can package/publish just fine. I wonder how they do that 🤔. Maybe we should study their repo structure to figure out how to fix the original packaging issue without getting rid of the workspace.

**Comment by sfdctaka** [comment]
I'm not so sure about the greatness if it broke the publishing. 

This is what they're doing to work around npm workspace.
https://github.com/forcedotcom/salesforcedx-vscode/blob/22df9f8632ddcf855277daac9aff8d331b6461f1/scripts/vsce-bundled-extension.ts#L76

I don't mind doing something similar. However, it will depend on the timing when we want to release this, which, I hope we can do soon and revisit this.

Our choice of using npm workspace was premature and without proper vetting, as shown by the current state of the repo. Getting npm workspace back into this repo is trivial. When we do we should also consider 2 future improvements which I noted in my earlier comment.

**Comment by maliroteh-sf** [comment]
I'll leave it to the rest of the team then. If most are ok with the approach of this PR then that's fine by me too.

**Review by haifeng-li-at-salesforce — APPROVED** [review]
LGTM

**Comment by ben-zhang-at-salesforce** [comment]
Thanks for fixing it and we verified the package vsix installed into vscode is doing the lsp diagnostic detection nicely. 
This change simplified the setup for the project. 

image

**Comment by sfdctaka** [comment]
@ben-zhang-at-salesforce @haifeng-li-at-salesforce Let's talk about this fix at the stand up later. Thanks for reviewing this PR.

I want to make sure we're not going too ahead of ourselves with wanting to release when we should be making perhaps a more formal change as like other repo which @maliroteh-sf suggested.

As noted in my comment, this PR was created as a simple stepping stone to get the package working. If we can get a consensus on the timing on the release and whether we want a formal change or not I'm more than happy to close this PR without merging it.

**Comment by khawkins** [comment]
> To simplify dependency management, dependencies from lsp/server have been moved to the root's package.json.

I think this depends on what you mean by "simplify". Doing so denormalizes the project structure, and from that standpoint tends to be more challenging to manage dependencies. What was the issue with keeping the dependency structure as is?

**Comment by khawkins** [comment]
Ah, saw your comments above about the errors caused by not moving dependencies.

If we're moving dependencies out of the sub-packages, we're not simply removing workspaces—we're basically removing any remaining value of having sub-packages at all. IMO we should either further restructure the project to reflect that reality (e.g. remove `package.json` configurations for those folders), or fix what's broken about having sub-packages.

**Comment by sfdctaka** [comment]
@khawkins This is the first of the many errors that I got greeted with when I ran `npx vsce package` without my changes in this PR.
```
t.arai@tarai-ltmwdhj salesforcedx-vscode-mobile % npx vsce package
Executing prepublish script 'npm run vscode:prepublish'...

> salesforcedx-vscode-mobile@0.3.0 vscode:prepublish
> npm run clean && npm run bundle:extension


> salesforcedx-vscode-mobile@0.3.0 clean
> rimraf out ./lsp/server/out ./lsp/client/out


> salesforcedx-vscode-mobile@0.3.0 bundle:extension
> esbuild ./src/extension.ts --bundle --outdir=out --format=cjs --target=es2020 --platform=node --external:vscode --external:@salesforce/core --external:@oclif/core --external:@salesforce/lwc-dev-mobile-core --minify --sourcemap

✘ [ERROR] Could not resolve "mobile-lsp-client"

    src/extension.ts:16:27:
      16 │ import * as lspClient from 'mobile-lsp-client';
         ╵                            ~~~~~~~~~~~~~~~~~~~

  You can mark the path "mobile-lsp-client" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "mobile-lsp-server"

    src/utils/constants.ts:8:53:
      8 │ export { CORE_EXTENSION_ID, SFDX_PROJECT_FILE } from 'mobile-lsp-server';
        ╵                                                      ~~~~~~~~~~~~~~~~~~~

  You can mark the path "mobile-lsp-server" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

2 errors
 ERROR  npm failed with exit code 1
```
Naturally I went to fix this but only to find more errors in a whack-a-mole scenario as I fix one after another.

To your concern about dependency of `lsp/server` moving to root project this is the error.
https://github.com/salesforce/salesforcedx-vscode-mobile/pull/154#issuecomment-2469677703
What I meant by simplifying is "consolidating" and not necessarily addressing potentially making it more difficult to managed dependency. However, the project is still small enough where `lsp/server` only has handful of dependencies while `lsp\server` has one I feel like we can revisit this in a near future in a separate work than from first making this repo to be able to create a redistributable package.

This, is one half of the big problem. The other half as I noted is **npm workspace** using sym link and that's not working nicely with `vsce package`. To fix this I got rid of **npm workspace**.

To your last point , yes, further work should be done in restructuring and trying to mirror how [salesforce-vscode](https://github.com/forcedotcom/salesforcedx-vscode) managed this.

**Comment by khawkins** [comment]
> To your last point , yes, further work should be done in restructuring and trying to mirror how [salesforce-vscode](https://github.com/forcedotcom/salesforcedx-vscode) managed this.

I guess my point there is, what are we trying to accomplish with this PR? I wouldn't choose to publish the extension in this post-merged state, without further work—it's in a quasi-completed state, in between a one-package and _n_-packages configuration. What's our goal here?

**Comment by sfdctaka** [comment]
@khawkins We're playing comment tag :). Saw your comment on removing `package.json` from sub-packages just now.

I actually tried that, thinking, since I consolidated dependencies I don't need `package.json`. So I deleted `package.json` in `lsp/client`. When I do that the root project this code in root project's `src/extension.ts`
```
import * as lspClient from '../lsp/client';
```
won't work.

**Comment by sfdctaka** [comment]
The goal is to get to minimally working vsix state. Because without being able to actually install it in VSCode as a vsix file we don't know if series of changes that we made over the last couple months is working. It's time when unit tests don't suffice to give us full confidence as we near release.

I'm not advocating for releasing at this time with this current structure. However, in my other PR(moving test folders), without a working vsix I wouldn't have been able to gain confidence if my work had broken anything. This is the time I believe we need to start testing with vsix package and not solely rely on unit tests.

The formal route is to mimic what salesforce-vscode is doing.

**Comment by khawkins** [comment]
Oh I'm not surprised there's more work required than simply removing the packages. For example, in a single-package integrated world, we should integrate all of the folders under `lsp/` into the standard `src/` folder structure, as all the code should be logically defined under a single package.

But we should just go ahead and do that, if so. I appreciate trying to get back to a working state, but I don't see a lot of point in committing a "stem the bleeding" PR to `main` in this case, because we're just trading one problem for another. Let's discuss offline, and figure out how we want to move forward. I'll leave it there for the moment.

**Pull request closed without merging**
